// Code generated by "stringer -type=CRCMode"; DO NOT EDIT

package firmware

import "fmt"

const _CRCMode_name = "NoCRCCRCPresent"

var _CRCMode_index = [...]uint8{0, 5, 15}

func (i CRCMode) String() string {
	if i < 0 || i >= CRCMode(len(_CRCMode_index)-1) {
		return fmt.Sprintf("CRCMode(%d)", i)
	}
	return _CRCMode_name[_CRCMode_index[i]:_CRCMode_index[i+1]]
}
